branches:
  only:
    - /^wip-[0-9]+\.[0-9]+$/
    - /[0-9]+\.[0-9]+$/

language: java
jdk:
  - oraclejdk8

env:
  global:
    - GRADLE_OPTS="-Dbuild.number=$TRAVIS_BUILD_NUMBER -Dbuild.vcs.number=$TRAVIS_COMMIT -Dbuild.vcs.branch=$TRAVIS_BRANCH -Dpublish.repo.userName=$REPO_USER -Dpublish.repo.password=$REPO_PSWD"

dist: trusty

before_install:
 - "chmod +x gradlew"
 - export JAVA_OPTS="-Xmx2048m -XX:MaxPermSize=386m"

install: ./gradlew assemble -Pskip.signing

after_success:
  - ./gradlew elasticsearch-hadoop-cascading:bintrayPublishBuild